In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pickle

In [3]:
df=pd.read_csv("Churn_Modelling.csv")

In [4]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
df=df.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [7]:
df

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
lb=LabelEncoder()

In [10]:
df['Gender']=lb.fit_transform(df['Gender'])

In [14]:
df['Gender'].value_counts()

Gender
1    5457
0    4543
Name: count, dtype: int64

In [15]:
on_geo=OneHotEncoder(sparse_output=False)

In [18]:
one_encoder=on_geo.fit_transform(df[['Geography']])

In [19]:
one_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [22]:
on_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [23]:
df2=pd.DataFrame(one_encoder, columns=on_geo.get_feature_names_out(['Geography']))

In [24]:
df2

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [26]:
df3=df.drop('Geography',axis=1)

In [29]:
df_final=pd.concat([df3,df2],axis=1)

In [30]:
df_final

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [32]:
with open('Label_encoder_gender.pkl','wb') as file:
    pickle.dump(lb,file)

In [34]:
with open('one_hot_encoder.pkl','wb') as file:
    pickle.dump(on_geo,file)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X=df_final.drop('Exited',axis=1)

In [37]:
y=df_final["Exited"]

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [39]:
sc=StandardScaler()

In [62]:
x_train=sc.fit_transform(X_train)

In [65]:
x_test=sc.transform(X_test)

In [42]:
with open('Scaler.pkl','wb') as file:
    pickle.dump(sc,file)

In [43]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [66]:
x_test

array([[-5.12501721e-01,  9.09111664e-01, -6.77299309e-01, ...,
        -1.02020406e+00,  1.73668197e+00, -5.63491843e-01],
       [-2.36046598e-01,  9.09111664e-01,  3.84298354e-01, ...,
         9.80196059e-01, -5.75810666e-01, -5.63491843e-01],
       [-4.61306328e-01, -1.09997489e+00,  4.80807232e-01, ...,
        -1.02020406e+00, -5.75810666e-01,  1.77464858e+00],
       ...,
       [ 8.59534812e-01, -1.09997489e+00,  7.70333868e-01, ...,
         9.80196059e-01, -5.75810666e-01, -5.63491843e-01],
       [ 4.70449825e-01,  9.09111664e-01, -9.66825944e-01, ...,
         9.80196059e-01, -5.75810666e-01, -5.63491843e-01],
       [-1.84851205e-01,  9.09111664e-01, -1.73715981e-03, ...,
        -1.02020406e+00,  1.73668197e+00, -5.63491843e-01]])

In [44]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [74]:
x_train.shape[1]

12

In [75]:
input_shape=(x_train.shape[1],)

In [76]:
input_shape

(12,)

In [50]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
]
    
    
)

In [52]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 64)                832       
                                                                 
 dense_6 (Dense)             (None, 32)                2080      
                                                                 
 dense_7 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [54]:
model2=Sequential([
    Dense(2,activation='relu',input_shape=(12,)),
    Dense(1,activation='sigmoid')
]
    
    
)

In [55]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 2)                 26        
                                                                 
 dense_10 (Dense)            (None, 1)                 3         
                                                                 
Total params: 29 (116.00 Byte)
Trainable params: 29 (116.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [56]:
opt=tf.optimizers.Adam(learning_rate=0.001)

In [57]:
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [58]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [59]:
early_stopping=EarlyStopping(monitor='val_loss',patience=15,restore_best_weights=True)

history=model.fit(
    X_train, y_train, epochs=10, batch_size=32, validation_data=(x_test,y_test), callbacks=[tensorflow_callback,early_stopping]
)

In [68]:
history=model.fit(
    x_train, y_train, epochs=120, batch_size=32, validation_data=(x_test,y_test), callbacks=[tensorflow_callback,early_stopping]
)

Epoch 1/120
250/250 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8612 - val_loss: 0.3401 - val_accuracy: 0.8605
Epoch 2/120
250/250 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8633 - val_loss: 0.3395 - val_accuracy: 0.8605
Epoch 3/120
250/250 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8635 - val_loss: 0.3393 - val_accuracy: 0.8630
Epoch 4/120
250/250 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8637 - val_loss: 0.3391 - val_accuracy: 0.8615
Epoch 5/120
250/250 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8645 - val_loss: 0.3366 - val_accuracy: 0.8610
Epoch 6/120
250/250 [==============================] - 0s 1ms/step - loss: 0.3284 - accuracy: 0.8655 - val_loss: 0.3390 - val_accuracy: 0.8620
Epoch 7/120
250/250 [==============================] - 0s 1ms/step - loss: 0.3273 - accuracy: 0.8644 - val_loss: 0.3365 - val_accuracy: 0.8620

model.save('model.h5')

In [78]:
model.save('model.h5')

In [70]:
%load_ext tensorboard

In [72]:
%tensorboard --logdir logs/fit/

Reusing TensorBoard on port 6006 (pid 26456), started 0:00:59 ago. (Use '!kill 26456' to kill it.)